services:
  exo-server:
    build:
      context: .
    container_name: exo-server
    env_file:
      - .env
    volume:
      .app.log:/app.log
    environment:
      - CONTAINERIZED=true
    ports:
      - "${EXTERNAL_PORT:-8356}:8356"
      - "${EXTERNAL_PORT_METRICS:-8000}:8000"
    restart: unless-stopped
    networks: 
      - exo-serve-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "${EXTERNAL_PORT_PROMETHEUS:-9090}:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    depends_on:
      - exo-server
    networks: 
      - exo-serve-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${EXTERNAL_PORT_GRAFANA:-3000}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER="${GF_SECURITY_ADMIN_USER}"
      - GF_SECURITY_ADMIN_PASSWORD="${GF_SECURITY_ADMIN_PASSWORD}"
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafanadata:/var/lib/grafana
    depends_on:
      - prometheus
    networks: 
      - exo-serve-network

networks:
  exo-serve-network: 
    driver: bridge

volumes:
  prometheusdata:
  grafanadata: