global:
  scrape_interval: 20s

scrape_configs:
  - job_name: "exo-server"
    metrics_path: /metrics
    static_configs:
    - targets: ["exo-server:8000"]
      labels:
        service: 'echo-server'
        environment: 'prod/development'
        